import { FiUsers } from 'react-icons/fi';
import { HiOutlineChartSquareBar } from 'react-icons/hi';
import { RiTodoLine } from 'react-icons/ri';
import {
  FaUser,
  FaUsers,
  FaClock,
  FaMoneyBillWave,
  FaCalendarAlt,
  FaChartBar,
} from 'react-icons/fa';
import { FaMoneyCheckAlt, FaMoneyBillAlt } from 'react-icons/fa';
import { BiTask, BiSolidChat } from 'react-icons/bi';
import { FaFileAlt, FaMoneyBill } from 'react-icons/fa';
import { BsCart4 } from 'react-icons/bs';
import { FaLock } from 'react-icons/fa';
import { FaUserPlus } from 'react-icons/fa';
import { FaBalanceScale } from 'react-icons/fa';
import {
  MdOutlineContactPhone,
  MdOutlineDns,
  MdLaunch,
  MdDashboard,
  MdOutlineDocumentScanner,
  MdPriceChange,
  MdOutlineSettings,
  MdSettingsSystemDaydream,
  MdCardMembership,
  MdSpaceDashboard,
  MdSwapHoriz,
  MdEqualizer,
  MdAssessment,
  MdReceipt,
  MdAdminPanelSettings,MdSupervisorAccount,
} from 'react-icons/md';
import { AiOutlineAppstoreAdd } from 'react-icons/ai';
import { LiaUserShieldSolid } from 'react-icons/lia';
import { RoutePermittedRole } from '@crema/constants/AppEnums';
import { TbFileInvoice } from 'react-icons/tb';
const routesConfig = [
  {
    id: 'launchpad',
    title: 'Launchpad',
    messageId: 'sidebar.launchpad',
    type: 'item',
    url: '/launchpad',
    icon: <MdLaunch />,
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    messageId: 'sidebar.dashboard',
    type: 'item',
    url: '/dashboard',
    icon: <MdDashboard />,
  },
  {
    id: 'salespayment',
    title: 'Sales & Payments',
    messageId: 'sidebar.salespayment',
    type: 'collapse',
    icon: <MdCardMembership />,
    children: [
      {
        id: 'quotations',
        title: 'Quotation',
        messageId: 'sidebar.salespayment.quotations',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <MdPriceChange />,
        url: '/salespayment/quotations',
      },
      {
        id: 'invoices',
        title: 'Invoices',
        messageId: 'sidebar.salespayment.invoices',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <TbFileInvoice />,
        url: '/salespayment/invoices',
      },
      {
        id: 'paymentsetup',
        title: 'Payments',
        messageId: 'payments.graph',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaMoneyBill />,
        url: '/salespayment/paymentsetup',
      },
      {
        id: 'customer',
        title: 'Customer',
        messageId: 'sidebar.salespayment.customer',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FiUsers />,
        url: '/salespayment/customer',
      },
      {
        id: 'productservices',
        title: 'Products & Services',
        messageId: 'sidebar.salespayment.productservices',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <MdSpaceDashboard />,
        url: '/salespayment/productservices',
      },
    ],
  },
  {
    id: 'purchases',
    title: 'Purchases',
    messageId: 'sidebar.purchases',
    type: 'collapse',
    icon: <BsCart4 />,
    children: [
      {
        id: 'purchaseOrder',
        title: 'Purchase Order',
        messageId: 'sidebar.purchases.purchaseOrder',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaFileAlt />,
        url: '/purchases/purchaseorder',
      },
      {
        id: 'bills',
        title: 'Bills',
        messageId: 'sidebar.purchases.bills',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <MdReceipt />,
        url: '/purchases/bills',
      },
      {
        id: 'payments',
        title: 'Payments',
        messageId: 'payments.graph',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaMoneyBill />,
        url: '/purchases/payments',
      },
      {
        id: 'vendors',
        title: 'Vendors',
        messageId: 'sidebar.purchases.vendors',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <LiaUserShieldSolid />,
        url: '/purchases/vendors',
      },
      {
        id: 'productservices',
        title: 'ProductServices',
        messageId: 'sidebar.salespayment.productservices',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <HiOutlineChartSquareBar />,
        url: '/purchases/productservices',
      },
    ],
  },
  {
    id: 'accounting',
    title: 'Accounting',
    messageId: 'sidebar.accounting',
    type: 'collapse',
    icon: <MdOutlineDocumentScanner />,
    children: [
      {
        id: 'chartofaccounts',
        title: 'Chart of Accounts',
        messageId: 'sidebar.accounting.chartofaccounts',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <MdEqualizer />,
        url: '/accounting/chartofaccounts',
      },
      {
        id: 'paymentCashVoucher',
        title: 'Payment Cash Voucher',
        messageId: 'sidebar.accounting.paymentCashVoucher',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaMoneyCheckAlt />,
        url: '/accounting/paymentcashvoucher',
      },
      {
        id: 'pettyCashVoucher',
        title: 'Petty Cash Voucher',
        messageId: 'sidebar.accounting.pettyCashVoucher',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaMoneyBillAlt />,
        url: '/accounting/pettycashvoucher',
      },
      {
        id: 'transactions',
        title: 'Transactions',
        messageId: 'sidebar.accounting.transactions',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <MdSwapHoriz />,
        url: '/accounting/transactions',
      },
      {
        id: 'trialBalance',
        title: 'Trial Balance',
        messageId: 'sidebar.accounting.trialBalance',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaBalanceScale />,
        url: '/accounting/trialbalance',
      },
    ],
  },

  {
    id: 'hr',
    title: 'HR',
    messageId: 'sidebar.hr',
    type: 'collapse',
    icon: <FaUser />,
    children: [
      {
        id: 'employees',
        title: 'Employees',
        messageId: 'sidebar.hr.employees',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaUsers />,
        url: '/hr/employees',
      },
      {
        id: 'timesheets',
        title: 'Timesheets',
        messageId: 'sidebar.hr.timesheets',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaClock />,
        url: '/hr/timesheets',
      },
      {
        id: 'chartofaccounts',
        title: 'Chart of Accounts',
        messageId: 'sidebar.hr.runPayroll',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaMoneyBillWave />,
        url: '/hr/runpayroll',
      },
      {
        id: 'leaves',
        title: 'Leaves',
        messageId: 'sidebar.hr.leaves',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaBalanceScale />,
        url: '/hr/leaves',
      },
      {
        id: 'calendar',
        title: 'Calendar',
        messageId: 'sidebar.hr.calendar',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaCalendarAlt />,
        url: '/hr/calendar',
      },
      {
        id: 'reports',
        title: 'Reports',
        messageId: 'sidebar.hr.reports',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaChartBar />,
        url: '/hr/reports',
      },
    ],
  },

  {
    id: 'apps',
    title: 'Apps',
    messageId: 'sidebar.apps',
    type: 'collapse',
    icon: <AiOutlineAppstoreAdd />,
    children: [
      {
        id: 'calender',
        title: 'Calender',
        messageId: 'sidebar.apps.calender',
        type: 'item',
        permittedRole: [RoutePermittedRole.User],
        icon: <BiTask />,
        url: '/apps/calender',
      },
      {
        id: 'contact',
        title: 'Contact',
        messageId: 'sidebar.apps.contact',
        type: 'item',
        permittedRole: [RoutePermittedRole.User],
        icon: <MdOutlineContactPhone />,
        url: '/apps/contact',
      },
      {
        id: 'todo',
        title: 'ToDo',
        messageId: 'sidebar.apps.todo',
        type: 'item',
        permittedRole: [RoutePermittedRole.User],
        count: 6,
        icon: <RiTodoLine />,
        color: '#48bb78',
        url: '/apps/todo',
      },
      {
        id: 'chat',
        title: 'Chat',
        messageId: 'sidebar.apps.chat',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <BiSolidChat />,
        url: '/apps/chat',
      },
      {
        id: 'scrumboard',
        title: 'Scrum Board',
        messageId: 'sidebar.apps.scrumboard',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <MdOutlineDns />,
        url: '/apps/scrum-board',
      },
    ],
  },
  {
    id: 'reports',
    title: 'Reports',
    messageId: 'sidebar.reports',
    type: 'item',
    icon: <MdAssessment />,
    url: '/reports',
  },
  {
    id: 'users',
    title: 'Users',
    messageId: 'sidebar.settings.users',
    type: 'collapse',
    icon: <FaUser />,
    children: [
      {
        id: 'adduser',
        title: 'Add User',
        messageId: 'sidebar.user.addUser',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaUserPlus />,
        url: '/users/user',
      },
      {
        id: 'assignPermission',
        title: 'Assign Permission',
        messageId: 'sidebar.user.assignPermission',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <FaLock />,
        url: '/user/assignpermission',
      },
      {
        id: 'roles',
        title: 'Roles',
        messageId: 'sidebar.user.role',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <MdSupervisorAccount />,
        url: '/user/roles',
      },
    ],
  },
  {
    id: 'configuration',
    title: 'Configuration',
    messageId: 'sidebar.configuration',
    type: 'item',
    icon: <MdSettingsSystemDaydream />,
    url: '/configuration',
  },
  {
    id: 'settings',
    title: 'Settings',
    messageId: 'sidebar.settings',
    type: 'item',
    icon: <MdOutlineSettings />,
    url: '/settings',
  },
  {
    id: 'admin',
    title: 'Admin',
    messageId: 'sidebar.admin',
    type: 'collapse',
    icon: <MdAdminPanelSettings />,
    children: [
      {
        id: 'admin-setting',
        title: 'Settings',
        messageId: 'sidebar.settings',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <MdOutlineSettings />,
        url: '/admin/settings',
      },
      {
        id: 'admin-configurations',
        title: 'Configurations',
        messageId: 'sidebar.admin.configurations',
        type: 'item',
        permittedRole: [RoutePermittedRole.Admin, RoutePermittedRole.User],
        icon: <MdSettingsSystemDaydream />,
        url: '/admin/configurations',
      },
    ],
  },
];
export default routesConfig;
